""" 
PRINCIPIOS SOLID
Aspectos a tener en cuenta en el desarrollo de software
1 - Mantenibilidad
2 - Reusabilidad
3 - Legibilidad
4 - Extensibilidad
SOLID:
S - SRP, SINGLE RESPONSABILITY PRINCIPIE (PRINCIPIO DE RESPONSABILIDAD UNICO)
O - OCP, PRINCIPIO DE ABIERTO/CERRADO
L - LSP, PRINCIPIO DE SUSTITUCION DE LISKOV
I - ISP, PRINCIPUO DE SEGREGACION DE INTERFAZ
D - DSP, PRINCIPIO DE INVERSION DE DEPENDENCIAS
 """